### ISSUE TITLE
yarn doesn

### ISSUE THREAD

**Issue by petershaw23** [cmfcmf/snapcast-control#5]
tried this on a pi4.
after installing yarn and running yarn install && yarn build i am getting following errors:
```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.4.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/pi/snapcast-control/frontend-react/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by cmfcmf** [comment]
Hi @petershaw23,

I cannot reproduce the problem. I tried running `yarn install` on my Pi3 and it worked. You could try running `yarn install --network-timeout 1000000` as suggested here: https://github.com/yarnpkg/yarn/issues/4890#issuecomment-358179301 and see if that fixes it.
Another option is to run `yarn install` and `yarn build` on a desktop PC and copy the `frontend-react/build` folder to your Pi.
